version: "3.8"

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: acl2_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: acl2_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    privileged: true
    environment:
      MONGO_URI: "mongodb://admin:password@acl2_mongo:27017/"
    command:
      [
        "fastapi",
        "run",
        "app/main.py",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    volumes:
      - ./acl2_api/app/logs:/app/app/logs

volumes:
  mongo_data:
    driver: local
