FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && \
    apt-get install -y acl2 && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

# Expone el puerto 8000 para FastAPI
EXPOSE 8000

# Ejecuta el servidor con el comando `fastapi run`
CMD ["fastapi", "run", "app/main.py"]
