version: '3.8'

services:
  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile.mongo
    container_name: acl2_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
